### ISSUE TITLE
API proposal (November 2024)

### ISSUE THREAD

**Issue by ihaveamac** [ihaveamac/GM9-lua-attempt#3]
Thinking about this again, I want to figure out what a GM9 lua API would look like. So let's try this out...

Most of these should be self-explanatory, I put notes next to ones that aren't.

For functions I have actually implemented on `real-lua-attempt`, there will be a :white_check_mark: with the actual function signature. Ones I think could be delayed until later I have a :arrow_right: next to it.

# Function naming

I'm not sure what's the best way to name these functions. For example, one that could check if the SD is mounted could be called:

* ~~`sdmounted()`~~
* `sd_mounted()`
* ~~`sd_is_mounted()`~~
* ~~`is_sd_mounted()`~~
* ~~`SDMounted()`~~
* ~~`SD_Mounted()`~~
* ~~`IsSDMounted()`~~
* ~~maybe more~~

~~I decided to go with the first one where possible but I'm not invested in that being the format.~~

# API proposal

## Global constants

* GM9VER
* SCRIPT
* CURRDIR
* GM9OUT
* HAX
* NANDSIZE
* CONSOLE_TYPE - "O3DS" or "N3DS"

## ui
* :white_check_mark: `void ui.echo(string text)`
* :white_check_mark: `bool ui.ask(string text)`
* :white_check_mark: `int ui.ask_hex(string text, int initial, int n_digits)`
* :white_check_mark: `int ui.ask_number(string text, int initial)`
* :white_check_mark: `string ui.ask_text(string prompt, string initial, int max_length)`
* :white_check_mark: `int ui.ask_selection(string prompt, array options)`
* `void ui.qr(string text, string data)`
* `void ui.clear()`
* :white_check_mark: `void ui.show_png(string path)`
* :white_check_mark: `void ui.show_text(string text)`
* :white_check_mark: `void ui.show_game_info(string text)`
* :white_check_mark: `void ui.show_text_viewer(string text)`
* :white_check_mark: `void ui.show_file_text_viewer(string path)`
* :white_check_mark: `void ui.format_bytes(int bytes)`

## fs

* :white_check_mark: `void fs.move(string src, string dst[, table opts {bool no_cancel, bool silent, bool overwrite_all, bool skip_all}])`
* :white_check_mark: `void fs.remove(string path[, table opts {bool recursive}])`
* :white_check_mark: `void fs.copy(string src, string dst[, table opts {bool calc_sha, bool sha1, bool no_cancel, bool silent, bool overwrite_all, bool skip_all, bool append_all, bool recursive}])`
* :white_check_mark: `void fs.mkdir(string path)`
* :white_check_mark: `array fs.list_dir(string path)`
* :white_check_mark: `array fs.stat(string path)`
* :white_check_mark: `array fs.stat_fs(string path)`
* :white_check_mark: `array fs.dir_info(string path)`
* :white_check_mark: `bool fs.allow(string path[, table flags {bool ask_all}])` - will prompt for permission
* :white_check_mark: `void fs.img_mount(string path)`
* :white_check_mark: `void fs.img_umount()`
* :white_check_mark: `string fs.get_img_mount()`
* :white_check_mark: `string fs.hash_file(string path, int offset, int size[, table opts {bool sha1}])`
* :white_check_mark: `string fs.hash_data(string data[, table opts {bool sha1}])`
* :white_check_mark: `bool fs.verify(string path)`
* :white_check_mark: `bool fs.exists(string path)`
* :white_check_mark: `bool fs.is_dir(string path)`
* :white_check_mark: `bool fs.is_file(string path)`
* :white_check_mark: `bool fs.sd_is_mounted()`
* :white_check_mark: `void fs.sd_switch()`
* :white_check_mark: `void fs.fix_cmacs(string path)`
* :white_check_mark: `string fs.read_file(string path, int offset, int size)`
* :white_check_mark: `int fs.write_file(string path, int offset, string data)`
* :white_check_mark: `void fs.truncate(string path)`

## title

* :arrow_right: `array title.get_installed(int media)` - some way to determine SD or NAND
* `array title.decrypt(string path bool inplace)` - The current `decrypt` only accepts one path, but isn't it possible to send it to somewhere else (0:/gm9/out)? It seems CryptGameFile only accepts 'inplace' though.
* `array title.encrypt(string path, bool inplace)` - Same as decrypt

## sys

* :white_check_mark: `void sys.boot(string path)`
* :white_check_mark: `void sys.reboot()`
* :white_check_mark: `void sys.power_off()`
* :white_check_mark: `string sys.region`
* :white_check_mark: `string sys.serial`
* :white_check_mark: `string sys.secureinfo_letter` - A or B, whichever is found, or `nil` if somehow it's missing
* :white_check_mark: `string sys.sys_id0`
* :white_check_mark: `string sys.emu_id0`
* :white_check_mark: `void sys.refresh_info()` - refreshes the upper five variables, automatically called by preload script, but can be manually invoked if SecureInfo_* is changed

## util

* :white_check_mark: `string util.bytes_to_hex(string data)`
* :white_check_mark: `string util.hex_to_bytes(string data)`

## io

This is a Lua built-in module but liolib.c can't be used as-is due to fopen and friends not working properly. To have this module we need to either:
* ~~make fopen/etc. work (maybe with a newlib device? i don't know what i'm doing here)~~
* ~~update liolib.c to use fatfs functions (this is much harder than it seems, i already tried this before, and could make it harder to update Lua)~~
* ~~create a custom io library in C~~
* create a custom io library in Lua, calling some internal interface for file i/o (this would probably be the easiest to write)

## os

This is also a Lua built-in module, but @Gruetzig has already re-implemented most, if not all, of it.

# Other stuff

* How should flags like silent, no_cancel, etc. be handled? I can think of a few ways:
  * ~~Call a function like `set_flags()` before~~
  * Use a table as an extra argument e.g. `fs.copy("S:/nand.bin", "0:/nand.bin", {silent=true, no_cancel=true})`
  * ~~Use bit flags as an extra argument e.g. `fs.copy("S:/nand.bin", "0:/nand.bin", CMD_SILENT | CMD_NO_CANCEL)`~~
* Is there an example of the cartdump command being used?
* :arrow_right: The SHA engine supports SHA224, but I can't see any place that it's actually used. I could probably add it though.

GM9 | Lua | Notes
-- | -- | --
goto | http://lua-users.org/wiki/GotoStatement |  
labelsel | ui.ask_selection |  
keychk |   |  
echo | ui.echo |  
qr |   |  
ask | ui.ask |  
input | ui.ask_input |  
filesel |   |  
dirsel |   |  
set | local var = value | Not using “local” will make global variables, leading to confusing errors if you don’t know what you’re doing
strsplit | string.find and string.sub |  
strrep | string.gsub |  
allow | fs.allow |  
cp | fs.copy |  
mv | fs.move |  
inject | fs.write_file |  
fill | fs.write_file |  
fdummy | fs.write_file |  
rm | fs.remove |  
mkdir | fs.mkdir |  
mount | fs.img_mount |  
umount | fs.img_umount |  
find |   |  
findnot |   |  
fget | fs.write_file |  
fset | fs.write_file |  
sha | fs.hash_file | Must check a corresponding .sha file manually
shaget | fs.hash_file |  
dumptxt | fs.write_file | The io compatibility module can open files in append mode
fixcmac | fs.fix_cmacs |  
verify | fs.verify |  
decrypt | title.decrypt |  
encrypt | title.encrypt |  
buildcia |   |  
install |   |  
extrcode |   |  
cmprcode |   |  
sdump |   |  
applyips |   |  
applybps |   |  
applybpm |   |  
textview | fs.show_file_text_viewer |  
cartdump |   |  
isdir | fs.is_dir |  
exist | fs.exists |  
boot | sys.boot |  
switchsd | fs.sd_switch |  
nextemu |   |  
reboot | sys.reboot |  
poweroff | sys.power_off |  
bkpt |   |  

### Preview

Unlike the `PREVIEW_MODE` GM9Script variable, this has been split into multiple functions.

Setting | Lua
-- | --
“quick” and “full” | (There is no alternative to view a Lua script as it’s running.)
“off” | ui.clear
text | ui.show_text
png file | ui.show_png
game icon | ui.show_game_info

**Comment by DarkRTA** [comment]
Couple of minor comments:

> I'm not sure what's the best way to name these functions. 

I think we should do `snake_case` here. While Lua's standard library opts to omit underscores, `snake_case` is easier to read and doesn't look too out of place.

> How should flags like silent, no_cancel, etc. be handled? I can think of a few ways: 

Avoid global state if possible and instead pass the flags as an argument to the function that needs them. Prefer using a table here unless you are extremely tight on memory.

**Comment by ihaveamac** [comment]
I updated various function names to use `snake_case`. Also added a section about io.

**Comment by ihaveamac** [comment]
I added a preload script that gets run before a lua file is (data/preload.lua). It loads libraries written in Lua, like my new io compatibility module. That module is still very incomplete, but the basic file opening, seeking, reading, and writing seems to work. (It's just a wrapper around fs.read_data and fs.write_data right now.)

**Comment by ihaveamac** [comment]
Continuing over here now: https://github.com/d0k3/GodMode9/pull/878
